[build]
	command = "# no build command"
	functions = "netlify/functions"
	publish = "dist"

[functions]
        node_bundler = "esbuild"
        external_node_modules = ["express"]
        included_files = ["all/channels.json"]