[build]
	command = "# no build command"
	functions = "netlify/functions"
	publish = "dist"

[functions]
        node_bundler = "esbuild"
        external_node_modules = ["express"]
        directory = "netlify/functions"
        included_files = ["to_backend/**.json"]